# I think, based on current standards, this file should be named
# docker-compose.yaml ; I'm not changing it so I can preserve the git trail

services:
  dummy-app:
    container_name: dummy-app
    image: debitkarma/cron-in-docker:0.0.2
    env_file: .env
    volumes:
      - ./log:/log
