[project]
name = "cron-in-docker"
version = "0.0.3"
requires-python = ">=3.11"
description = "toy project to mess around with scheduled docker tasks"
readme = "README.md"
dependencies = [
    "loguru>=0.7.2",
]
